### ISSUE TITLE
Why are new files created in Home folder?

### ISSUE THREAD

**Issue by sparky672** [pookjw/NightPatch#1]
Sierra 10.12.4 on Mid-2012 Mac Pro

After applying this patch, I see three new files in my Home folder....

```
_CodeSignature.bak
CoreBrightness.bak
NightPatchBuild
```

Why are these left here?  Can't these be moved, deleted, or hidden?

**Comment by pookjw** [comment]
NightPatch creates backup (system files) in your Home folder. When you revert changes, NightPatch will use that files. If you delete it, you can't revert using NightPatch. (have to re-install macOS)

**Comment by sparky672** [comment]
This is ugly and seems a little sloppy... can't we save these backups into their own folder called "NightPatch" and then save this folder someplace that makes more sense, like within the Library?

    /Library/NightPatch

**Comment by pookjw** [comment]
Thanks for opinion. I'll reflect on it next update.

**Comment by sparky672** [comment]
Thank you, and thank you for this tool!

**Comment by pookjw** [comment]
Updated just now. Backup will saved on ~/Library/NightPatch. If you want to move your old backup, try this command: `$ cd /tmp; curl -o NightPatch.zip https://codeload.github.com/pookjw/NightPatch/zip/master; unzip NightPatch.zip; cd NightPatch-master; ./NightPatch.sh -moveOldBackup`

**Comment by sparky672** [comment]
That moved everything alright.  However, now I have `NightPatch-master` folder and `NightPatch.zip` files left behind in my Home folder.

Wondering if this patch is good for ALL users of this computer?    If so, then maybe it should be in the main `/Library` and not inside `~/Library` for the user?

**Comment by pookjw** [comment]
I don't know why `NightPatch-master` and `NightPatch.zip` are created. Just delete it. And I think that's a good idea. I will reflect on it next update.

**Comment by sparky672** [comment]
I simply copied & pasted the terminal command above as you instructed.  The original three files were moved and `NightPatch-master` and `NightPatch.zip` were created.

**Comment by pookjw** [comment]
Updated Version 41
- Moved backup location `~/Library/NightPatch` to `/Library/NightPatch`.
- Removes `~/NightPatch-master` and `~/NightPatch.zip`.
