### ISSUE TITLE
The script doesn't work on 10.13.6

### ISSUE THREAD

**Issue by mrglutton** [pookjw/NightPatch#11]
Doesn't work on 10.13.6, but it did work on 10.13.5; 15" MBP Early 2011.

**Comment by aonez** [comment]
Check out this alternative: https://github.com/aonez/NightShiftPatcher

**Comment by aonez** [comment]
I’m not sure if @pookjw is currently maintaining NightPatch

**Comment by mrglutton** [comment]
Thanks a lot for info! will do later today, and will post back!

**Comment by mrglutton** [comment]
> Check out this alternative: https://github.com/aonez/NightShiftPatcher

I can confirm that this patched works on 10.13.6 on MacBook Pro 15-inch, Early 2011.

Thanks a lot!

**Comment by mrglutton** [comment]
This works: https://github.com/aonez/NightShiftPatcher
